### ISSUE TITLE
Destructive behavior

### ISSUE THREAD

**Issue by markparolisi** [voceconnect/voce-post-meta-widgets#3]
I haven't been able to debug this much yet, but here is what I'm seeing.

I register this to be active on a certain post type. This takes to steps. 
1. Adding a metadata field to hold the widgets 
`add_metadata_field( 'demo_meta', 'demo_widgets', 'Demo widget Area', 'widgets' );`
2. Adding the available widgets box to have something to put into the above field by adding my post type to the array returned from `voce_post_meta_widgets_post_types`

Both the container metabox and available widgets appear as expected and I can add widgets as expected. However, on post save, the meta is wiped out, and my page slug is changed. I've tried this on multiple posts and various post types and the behavior is the same. And the slug always reverts to the same slug from this other 'page' object I have. 

If I remove the available widgets metabox (using the filter), this destructive behavior does not occur.

**Comment by markparolisi** [comment]
Actually, hold on this. It looks like I'm using version 0.1.0. Let me upgrade to 0.1.1 and test again.

**Comment by matgargano** [comment]
ok, let me know.

**Comment by markparolisi** [comment]
Confirmed the same behavior in version 0.1.1

**Comment by kevinlangleyjr** [comment]
@matstars When you get some free time, can you address this issue so we can release this publicly?

Thanks!

**Comment by matgargano** [comment]
I believe @banderon fixed this, can you confirm @banderon?

**Comment by kevinlangleyjr** [comment]
@matstars @banderon Any word on this?

**Comment by banderon** [comment]
I don't recall exactly, but this sounds like the problem that was fixed in June. In any case, I've followed the above steps and do not see the problematic behavior occurring.  I've gone into two existing posts and added a few widgets to each one. Going back and forth and updating the widgets saves as expected and does not have any effect on other posts' widgets.

If someone else can give it a try and confirm, I'd consider this issue closed.

However, I think it's confusing to require adding the meta field via both the `add_post_type_support()` function as well as the `add_post_`voce_post_meta_widgets_post_types` filter. I'd recommend reworking the plugin to not include (or at least not require) this filter.
